# Please don't modify this file, without first checking if it makes sense to
# adopt for most other Kapost projects. Ideally, we would keep these files as
# similar as possible to ease maintainability. Instead, open a PR in the
# codeclimate-common repo at https://github.com/kapost/codeclimate-common

# This file is where app-specific Rubocop configs go. I wish every tool supported inherited configs...

inherit_from:
  - .rubocop.kapost.yml


